### ISSUE TITLE
[단순질문] JdbcRepository 인터페이스 @NoRepositoryBean

### ISSUE THREAD

**Issue by sjh836** [naver/spring-jdbc-plus#124]
안녕하세요?

아래 문서를 보니, JdbcRepository 인터페이스에 `@NoRepositoryBean` 를 붙여야하는게 아닌가 혼동이되네요..

* https://docs.spring.io/spring-data/relational/reference/repositories/definition.html
* `The intermediate repository interface is annotated with @NoRepositoryBean. Make sure you add that annotation to all repository interfaces for which Spring Data should not create instances at runtime.`

잘못이해한 부분이 있을까요?

**Comment by sjh836** [comment]
https://github.com/naver/spring-jdbc-plus/blob/main/spring-data-jdbc-plus-repository/src/main/java/com/navercorp/spring/data/jdbc/plus/repository/JdbcRepository.java#L33 에 `@NoRepositoryBean` 를 붙여야할까요? 이긴 했습니다..!

**Comment by IAM20** [comment]
@sjh836 아 네 필요해보이네요 감사합니다!

**Comment by sjh836** [comment]
확인감사합니다 (_ _)
