### ISSUE TITLE
Spring Data JDBC 3.0.0 Diif 반영

### ISSUE THREAD

**Issue by mhyeon-lee** [naver/spring-jdbc-plus#81]
@IAM20 Spring Data JDBC 3.0.0 이 릴리즈 되어 Diff 확인 후 반영이 필요할거 같습니다.

**Comment by IAM20** [comment]
Commit 이 약 900개여서 조금 걸릴것 같습니다. 약 2주 후인 12월 17일쯤을 목표로 진행해보겠습니다.

**Comment by benelog** [comment]
3.0에서 뭐가 바뀌었는지 정리된 문서를 찾기가 어렵군요.

대신 What'new 페이지도 없앤 commit이 보입니다.

**Comment by mhyeon-lee** [comment]
@IAM20 기준 JDK 버전을 JDK 17 로 잡아야 될 수도 있습니다.

**Comment by airoasis** [comment]
이제야 Spring Data JDBC를 접하고 사용해보려고 하는개발자입니다. 혹시 3.0 에서도 partial update는 여전히 https://spring.io/blog/2022/01/20/spring-data-jdbc-how-can-i-do-a-partial-update-of-an-aggregate-root 이게 best practice 인가요?

**Comment by IAM20** [comment]
@airoasis partial update 시 삭제하고 재생성하는 것은 3.0.0 에서도 그대로입니다. 다만 이전엔 루프안에서 하나씩 지웠다면 이제는 batchUpdate 를 사용하기에 DBMS 에 따라 이전보다는 빠른 성능을 보일것 같습니다.

그래도 여전히 삭제하고 재생성하는 것은 그대로이기 때문에 위 글에서의 custom method 또는 string based query 를 사용하는 것이 리소스 측면에는 효율적일 것 같습니다 :)
